# Generated by Django 5.2.9 on 2026-09-11 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('po_num', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('UPST', 'Unposted'), ('OPEN', 'Shipped'), ('CMPL', 'Complete')], default='Unposted', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Entry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('quantity_on_hand', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order_Data',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted', models.BooleanField(default=False)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('po_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase_order')),
            ],
        ),
    ]
