# Generated by Django 5.2.9 on 2026-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_data',
            name='order_date',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
