# Generated by Django 5.2.9 on 2026-08-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_entry',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('po_num', models.IntegerField()),
                ('order_date', models.DateField()),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField(default=0)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
            ],
        ),
    ]
