# Generated by Django 5.2.9 on 2026-09-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_purchase_order_data_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order_data',
            name='posted',
        ),
    ]
