# Generated by Django 5.2.9 on 2026-09-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_entry_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
